### PR TITLE
Add varargs parameter factory to SQLFragment

### PR DESCRIPTION
**Pull request by SentryMan**
idk I don't like doing `Arrays.asList` all of the time

### CODE REVIEW

**Comment by bowbahdoe** [comment]
This opens up a footgun if you want to pass an array parameter. Like

```java
String[] strings = { "a", "b", "c" };
SQLFragment.of("""
WHERE id = ANY(?)
""", List.of(strings));
```

which is what the postgres driver wants. This footgun also exists with `Arrays.asList` but

* It is already there and you may be aware of it from other things
* This API is kinda unimportant when string templates come. i.e.

```java
SQLFragment.of($"""
WHERE id = ANY(\{strings})
""");
```

Is a much better API overall.

**Comment by SentryMan** [comment]
> This API is kinda unimportant when string templates come. 

maybe so, but they aren't here

**Comment by bowbahdoe** [comment]
I'm willing to wait

**Comment by SentryMan** [comment]
I see

**Pull request closed without merging**
